// Writes the two Supabase auth email templates from the same shell the
// programme emails use, so every message the site sends looks the same.
// Run with `npm run email:templates`, then paste each file's markup into
// Supabase → Authentication → Email Templates (see the README beside them).

import fs from "node:fs";
import path from "node:path";
import { emailShell } from "@/lib/email/layout";

const SITE = "{{ .SiteURL }}";
const out = path.resolve(process.cwd(), "supabase/templates");

const header = (template: string) => `<!--
  Supabase → Authentication → Email Templates → "${template}".
  Paste the markup below into the Message body field.

  GENERATED by tools/gen-auth-templates.ts from src/lib/email/layout.ts;
  edit those and run \`npm run email:templates\` rather than this file.

  The link uses the token_hash style, which calls /auth/confirm on the
  site directly rather than bouncing through Supabase's verify endpoint
  first. {{ .SiteURL }} must therefore be the live site, not localhost.
-->
`;

const confirm = emailShell({
  site: SITE,
  siteLabel: "thewtchroom.co.uk",
  programme: "Your account",
  heading: "Confirm your email address",
  paragraphs: [
    "Thanks for registering with The Watch Room. Confirm this address and your account is live.",
    "If you asked to join the pre-alpha or applied to the advisor programme, that is filed at the same moment, and your account page shows where it stands.",
  ],
  cta: { label: "Confirm email", href: `${SITE}/auth/confirm?token_hash={{ .TokenHash }}&type=email&next=/standby` },
  showLink: true,
  note: "Didn't register with The Watch Room? Ignore this email. No account is created until the address is confirmed.",
});

const reset = emailShell({
  site: SITE,
  siteLabel: "thewtchroom.co.uk",
  programme: "Your account",
  heading: "Set a new password",
  paragraphs: [
    "Someone asked to reset the password for this account. Use the button below to choose a new one. The link can only be used once.",
  ],
  cta: { label: "Set new password", href: `${SITE}/auth/confirm?token_hash={{ .TokenHash }}&type=recovery&next=/reset-password` },
  showLink: true,
  note: "Didn't ask for this? Ignore this email. Your password stays as it is until the link above is used.",
});

fs.writeFileSync(path.join(out, "confirm-signup.html"), header("Confirm signup") + confirm + "\n");
fs.writeFileSync(path.join(out, "reset-password.html"), header("Reset password") + reset + "\n");
console.log("wrote supabase/templates/confirm-signup.html and reset-password.html");
